# Generated by Django 5.0 on 2026-01-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='text',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
